@startuml

(*) -->[项目启动] "提交需求文档"
if "需求无异议" then
    -->[true] "建立WorkTile，开始项目管控" 
    -->[需求转化] "画活动图"
    note left: 产品介入，避免需求理解错误
    -->[接口定义] "前后端沟通+swagger"
    note left: 定义好的接口是已经达到共识的，\n过程中应该避免修改，修改必须沟通与通知
    if "前后端分离" then
    -->[后端] "实现已经定义好的接口"
    -->[完成相同功能点] ===完成相同功能点===
    else
    -->[前端] "实现对应接口的页面"
    --> ===完成相同功能点===
    -->[测试] "功能点测试" 
    -->[重复所有功能点] "前后端完成"
    -->[集成测试] (*)
    endif

else
    -->[false] "修改需求"
    note left: 项目开始后的需求有权利拒绝;\n无法拒绝的新需求将记录，\n有权利追责
@enduml 