@startuml

(*) -->[index] "两个功能：新增规则，调用规则"
if "" then 
    -->[调用规则] "进入调用页面"
    -->[规则列表] "选择规则"
    note left: 动态多条规则？
    -->[选择实体] "填写实体属性"
    -->[提交规则] "返回结果"

else 
    -->[新增规则] "进入新增页面"
    if "" then 
        -->[规则填写] "文本框+语法检查？+示例"
        -->[规则验证] "提交填写的规则"
        note right: 验证是否可用
        -->[通过验证] "填写规则名称"
        note right: 数据库验证是否有重复规则
        -->[提交规则] "规则存储"
    else 
        -->[决策表提交] "上传决策表"
        -->[通过验证] "填写规则名称"
    endif

endif



@enduml