@startuml

    class EagleEyeController{
      -ModelCalculationService
      -EagleEyeService
      +baseInfo()
      +totalInfo()
      +reportJson()
      +reportList()
      +reportListNum()
      +reportListDown()
    }
    class ApiController{
      -UnityApiService
      +credit()
      +getResultCredit()
      +smsCredit()
      +callCredit()
    }
    class ApiCommonController{
      -BaseApiService
      -UnityApiService
      -SuggestionConfigMapper
      +getSuggestion()
    }

    interface BaseApiService
    interface EagleEyeService
    interface ModelCalculationService
    interface UnityApiService
    interface UnityMongoService
    interface UnitySqlService

    interface PersonPipelineMapper
    interface PhoneAttributionMapper
    interface SuggestionConfigMapper

    class BaseApiServiceImpl implements BaseApiService{
      -PhoneAttributionMapper
      +saveFile()
      +getMobileBelong()
      +formatOperation()
    }

    class EagleEyeServiceImpl implements EagleEyeService{
      -BaseApiService
      -UnityApiService
      -UnitySqlService
      +getBaseInfo()
      +getTotalInfo()
      +getReportJson()
      +uidCheck()
      +loadReportExcel()
    }
    class ModelCalculationServiceImpl implements ModelCalculationService{
      -UnitySqlService
      +getCalculationResult()
    }
    class UnityApiServiceImpl implements UnityApiService{
      -BaseApiService
      +initAccount()
      +login()
      +sms()
      +verify()
      +getDataFromDC()
    }
    class UnityMongoServiceImpl implements UnityMongoService{
      -MongoTemplate
      +saveBaseInfo()
      +count()
      +insert()
    }
    class UnitySqlServiceImpl implements UnitySqlService{
      -PersonPipelineMapper
      +getPipelineById()
      +getResultByRid()
      +getPipelineListByUid()
    }

    ModelCalculationService *-->EagleEyeController
    EagleEyeService *-->EagleEyeController
    UnityMongoService *-->EagleEyeController

    BaseApiService *-->EagleEyeService
    UnityApiService *-->EagleEyeService
    UnitySqlService *-->EagleEyeService

    BaseApiService *-->UnityApiService

    PersonPipelineMapper *-->UnitySqlService

    BaseApiService *-->ApiCommonController
    UnityApiService *-->ApiCommonController
    SuggestionConfigMapper *-->ApiCommonController

    UnityApiService *-->ApiController

    PhoneAttributionMapper *-->BaseApiServiceImpl

@enduml
